#/bin/sh

./a.out ../../tiger/testcases/test1.tig	&& echo 1
./a.out ../../tiger/testcases/test2.tig	&& echo 2
./a.out ../../tiger/testcases/test3.tig	&& echo 3
./a.out ../../tiger/testcases/test4.tig	&& echo 4
./a.out ../../tiger/testcases/test5.tig	&& echo 5
./a.out ../../tiger/testcases/test6.tig	&& echo 6
./a.out ../../tiger/testcases/test7.tig	&& echo 7
./a.out ../../tiger/testcases/test8.tig	&& echo 8
./a.out ../../tiger/testcases/test9.tig	&& echo 9
./a.out ../../tiger/testcases/test10.tig	&& echo 10
./a.out ../../tiger/testcases/test11.tig	&& echo 11
./a.out ../../tiger/testcases/test12.tig	&& echo 12
./a.out ../../tiger/testcases/test13.tig	&& echo 13
./a.out ../../tiger/testcases/test14.tig	&& echo 14
./a.out ../../tiger/testcases/test15.tig	&& echo 15
./a.out ../../tiger/testcases/test16.tig	&& echo 16
./a.out ../../tiger/testcases/test17.tig	&& echo 17
./a.out ../../tiger/testcases/test18.tig	&& echo 18
./a.out ../../tiger/testcases/test19.tig	&& echo 19
./a.out ../../tiger/testcases/test20.tig	&& echo 20
./a.out ../../tiger/testcases/test21.tig	&& echo 21
./a.out ../../tiger/testcases/test22.tig	&& echo 22
./a.out ../../tiger/testcases/test23.tig	&& echo 23
./a.out ../../tiger/testcases/test24.tig	&& echo 24
./a.out ../../tiger/testcases/test25.tig	&& echo 25
./a.out ../../tiger/testcases/test26.tig	&& echo 26
./a.out ../../tiger/testcases/test27.tig	&& echo 27
./a.out ../../tiger/testcases/test28.tig	&& echo 28
./a.out ../../tiger/testcases/test29.tig	&& echo 29
./a.out ../../tiger/testcases/test30.tig	&& echo 30
./a.out ../../tiger/testcases/test31.tig	&& echo 31
./a.out ../../tiger/testcases/test32.tig	&& echo 32
./a.out ../../tiger/testcases/test33.tig	&& echo 33
./a.out ../../tiger/testcases/test34.tig	&& echo 34
./a.out ../../tiger/testcases/test35.tig	&& echo 35
./a.out ../../tiger/testcases/test36.tig	&& echo 36
./a.out ../../tiger/testcases/test37.tig	&& echo 37
./a.out ../../tiger/testcases/test38.tig	&& echo 38
./a.out ../../tiger/testcases/test39.tig	&& echo 39
./a.out ../../tiger/testcases/test40.tig	&& echo 40
./a.out ../../tiger/testcases/test41.tig	&& echo 41
./a.out ../../tiger/testcases/test42.tig	&& echo 42
./a.out ../../tiger/testcases/test43.tig	&& echo 43
./a.out ../../tiger/testcases/test44.tig	&& echo 44
./a.out ../../tiger/testcases/test45.tig	&& echo 45
./a.out ../../tiger/testcases/test46.tig	&& echo 46
./a.out ../../tiger/testcases/test47.tig	&& echo 47
./a.out ../../tiger/testcases/test48.tig	&& echo 48
./a.out ../../tiger/testcases/test49.tig	&& echo 49
./a.out ../../tiger/testcases/queens.tig	&& echo queens
./a.out ../../tiger/testcases/merge.tig	&& echo merge